# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-quarkus-app
spec:
  selector:
    matchLabels:
      app: kustomize-quarkus-app
  template:
    metadata:
      labels:
        app: kustomize-quarkus-app
        environment: test  # Voeg deze nieuwe label toe
        app1: kustomize-quarkus-app  # Voeg deze nieuwe label toe
