apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: kustomize-quarkus-app
    newName: ghcr.io/vrecon/kustomize-quarkus
    newTag: latest  # Dit wordt automatisch geüpdatet door de GitHub Action
