# base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kustomize-quarkus-app
spec:
  type: NodePort  # Verander dit van ClusterIP naar NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kustomize-quarkus-app
