# overlays/development/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base  # pas dit aan naar het correcte relatieve pad
namePrefix: dev-

images:
  - name: kustomize-quarkus-app
    newName: kustomize-quarkus-app
    newTag: dev
